//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class MeiTanDataEntity : BaseEntity
    {
        
        public MeiTanDataEntity()
        {
        }
        
        private int m_ID;
        
        public int ID
        {
            get
            {
return this.m_ID;
            }
            set
            {
this.m_ID = value;
            }
        }
        
        private int m_UserID;
        
        public int UserID
        {
            get
            {
return this.m_UserID;
            }
            set
            {
this.m_UserID = value;
            }
        }
        
        private string m_GongXu;
        
        public string GongXu
        {
            get
            {
return this.m_GongXu;
            }
            set
            {
this.m_GongXu = value;
            }
        }
        
        private System.DateTime m_FaBuRiQi;
        
        public System.DateTime FaBuRiQi
        {
            get
            {
return this.m_FaBuRiQi;
            }
            set
            {
this.m_FaBuRiQi = value;
            }
        }
        
        private System.DateTime m_XinXiYouXiaoQi;
        
        public System.DateTime XinXiYouXiaoQi
        {
            get
            {
return this.m_XinXiYouXiaoQi;
            }
            set
            {
this.m_XinXiYouXiaoQi = value;
            }
        }
        
        private string m_MeiZhong;
        
        public string MeiZhong
        {
            get
            {
return this.m_MeiZhong;
            }
            set
            {
this.m_MeiZhong = value;
            }
        }
        
        private string m_PinZhong;
        
        public string PinZhong
        {
            get
            {
return this.m_PinZhong;
            }
            set
            {
this.m_PinZhong = value;
            }
        }
        
        private string m_THSheng;
        
        public string THSheng
        {
            get
            {
return this.m_THSheng;
            }
            set
            {
this.m_THSheng = value;
            }
        }
        
        private string m_THShi;
        
        public string THShi
        {
            get
            {
return this.m_THShi;
            }
            set
            {
this.m_THShi = value;
            }
        }
        
        private string m_JHSheng;
        
        public string JHSheng
        {
            get
            {
return this.m_JHSheng;
            }
            set
            {
this.m_JHSheng = value;
            }
        }
        
        private string m_JHShi;
        
        public string JHShi
        {
            get
            {
return this.m_JHShi;
            }
            set
            {
this.m_JHShi = value;
            }
        }
        
        private int m_ShuLiang;
        
        public int ShuLiang
        {
            get
            {
return this.m_ShuLiang;
            }
            set
            {
this.m_ShuLiang = value;
            }
        }
        
        private int m_JiaGe;
        
        public int JiaGe
        {
            get
            {
return this.m_JiaGe;
            }
            set
            {
this.m_JiaGe = value;
            }
        }
        
        private string m_BaoJiaFangShi;
        
        public string BaoJiaFangShi
        {
            get
            {
return this.m_BaoJiaFangShi;
            }
            set
            {
this.m_BaoJiaFangShi = value;
            }
        }
        
        private string m_JieSuanFangShi;
        
        public string JieSuanFangShi
        {
            get
            {
return this.m_JieSuanFangShi;
            }
            set
            {
this.m_JieSuanFangShi = value;
            }
        }
        
        private double m_FaReLiang;
        
        public double FaReLiang
        {
            get
            {
return this.m_FaReLiang;
            }
            set
            {
this.m_FaReLiang = value;
            }
        }
        
        private double m_LiDu;
        
        public double LiDu
        {
            get
            {
return this.m_LiDu;
            }
            set
            {
this.m_LiDu = value;
            }
        }
        
        private double m_HanLiuLiang;
        
        public double HanLiuLiang
        {
            get
            {
return this.m_HanLiuLiang;
            }
            set
            {
this.m_HanLiuLiang = value;
            }
        }
        
        private double m_HuiFen;
        
        public double HuiFen
        {
            get
            {
return this.m_HuiFen;
            }
            set
            {
this.m_HuiFen = value;
            }
        }
        
        private double m_ShuiFen;
        
        public double ShuiFen
        {
            get
            {
return this.m_ShuiFen;
            }
            set
            {
this.m_ShuiFen = value;
            }
        }
        
        private double m_HuiFa;
        
        public double HuiFa
        {
            get
            {
return this.m_HuiFa;
            }
            set
            {
this.m_HuiFa = value;
            }
        }
        
        private double m_GuDingTan;
        
        public double GuDingTan
        {
            get
            {
return this.m_GuDingTan;
            }
            set
            {
this.m_GuDingTan = value;
            }
        }
        
        private double m_JiXieQiangDu;
        
        public double JiXieQiangDu
        {
            get
            {
return this.m_JiXieQiangDu;
            }
            set
            {
this.m_JiXieQiangDu = value;
            }
        }
        
        private double m_GuiGe;
        
        public double GuiGe
        {
            get
            {
return this.m_GuiGe;
            }
            set
            {
this.m_GuiGe = value;
            }
        }
        
        private double m_KangSuiQiangDu;
        
        public double KangSuiQiangDu
        {
            get
            {
return this.m_KangSuiQiangDu;
            }
            set
            {
this.m_KangSuiQiangDu = value;
            }
        }
        
        private double m_LaiMoQianDu;
        
        public double LaiMoQianDu
        {
            get
            {
return this.m_LaiMoQianDu;
            }
            set
            {
this.m_LaiMoQianDu = value;
            }
        }
        
        private double m_FanYingXing;
        
        public double FanYingXing
        {
            get
            {
return this.m_FanYingXing;
            }
            set
            {
this.m_FanYingXing = value;
            }
        }
        
        private double m_QiKongLv;
        
        public double QiKongLv
        {
            get
            {
return this.m_QiKongLv;
            }
            set
            {
this.m_QiKongLv = value;
            }
        }
        
        private double m_JiaoMoHanLiang;
        
        public double JiaoMoHanLiang
        {
            get
            {
return this.m_JiaoMoHanLiang;
            }
            set
            {
this.m_JiaoMoHanLiang = value;
            }
        }
        
        private double m_LianJieZhiShu;
        
        public double LianJieZhiShu
        {
            get
            {
return this.m_LianJieZhiShu;
            }
            set
            {
this.m_LianJieZhiShu = value;
            }
        }
        
        private double m_ReWenDingXing;
        
        public double ReWenDingXing
        {
            get
            {
return this.m_ReWenDingXing;
            }
            set
            {
this.m_ReWenDingXing = value;
            }
        }
        
        private double m_HuiRongRongXing;
        
        public double HuiRongRongXing
        {
            get
            {
return this.m_HuiRongRongXing;
            }
            set
            {
this.m_HuiRongRongXing = value;
            }
        }
        
        private double m_KeMoXing;
        
        public double KeMoXing
        {
            get
            {
return this.m_KeMoXing;
            }
            set
            {
this.m_KeMoXing = value;
            }
        }
        
        private string m_XiangXiLeiRong;
        
        public string XiangXiLeiRong
        {
            get
            {
return this.m_XiangXiLeiRong;
            }
            set
            {
this.m_XiangXiLeiRong = value;
            }
        }
        
        private string m_IsTiGongYunShu;
        
        public string IsTiGongYunShu
        {
            get
            {
return this.m_IsTiGongYunShu;
            }
            set
            {
this.m_IsTiGongYunShu = value;
            }
        }
        
        private string m_YunshuFangShi;
        
        public string YunshuFangShi
        {
            get
            {
return this.m_YunshuFangShi;
            }
            set
            {
this.m_YunshuFangShi = value;
            }
        }
        
        private string m_YunShuShuoMing;
        
        public string YunShuShuoMing
        {
            get
            {
return this.m_YunShuShuoMing;
            }
            set
            {
this.m_YunShuShuoMing = value;
            }
        }
        
        private int m_DianJiLiang;
        
        public int DianJiLiang
        {
            get
            {
return this.m_DianJiLiang;
            }
            set
            {
this.m_DianJiLiang = value;
            }
        }
        
        private string m_LianXiRen;
        
        public string LianXiRen
        {
            get
            {
return this.m_LianXiRen;
            }
            set
            {
this.m_LianXiRen = value;
            }
        }
        
        private string m_Phone;
        
        public string Phone
        {
            get
            {
return this.m_Phone;
            }
            set
            {
this.m_Phone = value;
            }
        }
        
        private string m_Mail;
        
        public string Mail
        {
            get
            {
return this.m_Mail;
            }
            set
            {
this.m_Mail = value;
            }
        }
        
        private string m_Fax;
        
        public string Fax
        {
            get
            {
return this.m_Fax;
            }
            set
            {
this.m_Fax = value;
            }
        }
        
        private string m_Mobile;
        
        public string Mobile
        {
            get
            {
return this.m_Mobile;
            }
            set
            {
this.m_Mobile = value;
            }
        }
        
        private string m_Province;
        
        public string Province
        {
            get
            {
return this.m_Province;
            }
            set
            {
this.m_Province = value;
            }
        }
        
        private string m_City;
        
        public string City
        {
            get
            {
return this.m_City;
            }
            set
            {
this.m_City = value;
            }
        }
        
        private string m_Address;
        
        public string Address
        {
            get
            {
return this.m_Address;
            }
            set
            {
this.m_Address = value;
            }
        }
        
        private string m_PostCode;
        
        public string PostCode
        {
            get
            {
return this.m_PostCode;
            }
            set
            {
this.m_PostCode = value;
            }
        }
        
        private bool m_IsTongGuo;
        
        public bool IsTongGuo
        {
            get
            {
return this.m_IsTongGuo;
            }
            set
            {
this.m_IsTongGuo = value;
            }
        }
        
        private string m_YuanYin;
        
        public string YuanYin
        {
            get
            {
return this.m_YuanYin;
            }
            set
            {
this.m_YuanYin = value;
            }
        }
    }
}
