//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class QiYeXinXiDataEntity : BaseEntity
    {
        
        public QiYeXinXiDataEntity()
        {
        }
        
        private int m_UserID;
        
        public int UserID
        {
            get
            {
return this.m_UserID;
            }
            set
            {
this.m_UserID = value;
            }
        }
        
        private string m_GSMingCheng;
        
        public string GSMingCheng
        {
            get
            {
return this.m_GSMingCheng;
            }
            set
            {
this.m_GSMingCheng = value;
            }
        }
        
        private string m_GSXingZhi;
        
        public string GSXingZhi
        {
            get
            {
return this.m_GSXingZhi;
            }
            set
            {
this.m_GSXingZhi = value;
            }
        }
        
        private string m_QiYeLeiXing;
        
        public string QiYeLeiXing
        {
            get
            {
return this.m_QiYeLeiXing;
            }
            set
            {
this.m_QiYeLeiXing = value;
            }
        }
        
        private System.DateTime m_ChengLiRiQi;
        
        public System.DateTime ChengLiRiQi
        {
            get
            {
return this.m_ChengLiRiQi;
            }
            set
            {
this.m_ChengLiRiQi = value;
            }
        }
        
        private int m_ZhuCeZiJin;
        
        public int ZhuCeZiJin
        {
            get
            {
return this.m_ZhuCeZiJin;
            }
            set
            {
this.m_ZhuCeZiJin = value;
            }
        }
        
        private string m_FaRenDaiBiao;
        
        public string FaRenDaiBiao
        {
            get
            {
return this.m_FaRenDaiBiao;
            }
            set
            {
this.m_FaRenDaiBiao = value;
            }
        }
        
        private string m_GSJieShao;
        
        public string GSJieShao
        {
            get
            {
return this.m_GSJieShao;
            }
            set
            {
this.m_GSJieShao = value;
            }
        }
        
        private string m_JingYingFanWei;
        
        public string JingYingFanWei
        {
            get
            {
return this.m_JingYingFanWei;
            }
            set
            {
this.m_JingYingFanWei = value;
            }
        }
    }
}
