//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class QiYeLeiXingDataEntity : BaseEntity
    {
        
        public QiYeLeiXingDataEntity()
        {
        }
        
        private int m_ID;
        
        public int ID
        {
            get
            {
return this.m_ID;
            }
            set
            {
this.m_ID = value;
            }
        }
        
        private string m_Qiyeleixing;
        
        public string Qiyeleixing
        {
            get
            {
return this.m_Qiyeleixing;
            }
            set
            {
this.m_Qiyeleixing = value;
            }
        }
    }
}
