//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class ZhanNeiXinJianDataEntity : BaseEntity
    {
        
        public ZhanNeiXinJianDataEntity()
        {
        }
        
        private int m_ID;
        
        public int ID
        {
            get
            {
return this.m_ID;
            }
            set
            {
this.m_ID = value;
            }
        }
        
        private int m_ToUserId;
        
        public int ToUserId
        {
            get
            {
return this.m_ToUserId;
            }
            set
            {
this.m_ToUserId = value;
            }
        }
        
        private int m_FromUserId;
        
        public int FromUserId
        {
            get
            {
return this.m_FromUserId;
            }
            set
            {
this.m_FromUserId = value;
            }
        }
        
        private string m_LiuYanNeiRong;
        
        public string LiuYanNeiRong
        {
            get
            {
return this.m_LiuYanNeiRong;
            }
            set
            {
this.m_LiuYanNeiRong = value;
            }
        }
        
        private System.DateTime m_ShiJian;
        
        public System.DateTime ShiJian
        {
            get
            {
return this.m_ShiJian;
            }
            set
            {
this.m_ShiJian = value;
            }
        }
        
        private bool m_IsRead;
        
        public bool IsRead
        {
            get
            {
return this.m_IsRead;
            }
            set
            {
this.m_IsRead = value;
            }
        }
        
        private bool m_IsDelete;
        
        public bool IsDelete
        {
            get
            {
return this.m_IsDelete;
            }
            set
            {
this.m_IsDelete = value;
            }
        }
    }
}
