//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusFacade
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Reflection;
    using System.Data.SqlClient;
    using DataLogic;
    using BusEntity;
    
    
    public class CityBusFacade
    {
        
        public CityBusFacade()
        {
        }
        
        // 根据主键cityName返回指定的City实体
        public static CityBusEntity GetEntity(string cityName)
        {
            CityByPK exec = new CityByPK();
            exec.CityName = cityName;
            CityBusEntity obj = new CityBusEntity();
            obj.MetaDataTable = exec.ExecDataTable();
            return obj;
        }
        
        // 返回所有City
        public static DataTable GetList()
        {
            CityByAll exec = new CityByAll();
            return exec.ExecDataTable();
        }
        // 根据省份proID返回所有City
        public static DataTable GetList(int proID)
        {
            CityByProID exec = new CityByProID();
            exec.ProID = proID;
            return exec.ExecDataTable();
        }
    }
}
