//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusFacade
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Reflection;
    using System.Data.SqlClient;
    using DataLogic;
    using BusEntity;
    
    
    public class GongShiXingZhiBusFacade
    {
        
        public GongShiXingZhiBusFacade()
        {
        }
        
        // 根据主键ID返回指定的GongShiXingZhi实体
        public static GongShiXingZhiBusEntity GetEntity(int ID)
        {
            GongShiXingZhiByPK exec = new GongShiXingZhiByPK();
            exec.ID = ID;
            GongShiXingZhiBusEntity obj = new GongShiXingZhiBusEntity();
            obj.MetaDataTable = exec.ExecDataTable();
            return obj;
        }
        
        // 返回所有GongShiXingZhi
        public static DataTable GetList()
        {
            GongShiXingZhiByAll exec = new GongShiXingZhiByAll();
            return exec.ExecDataTable();
        }
    }
}
