//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusFacade
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Reflection;
    using System.Data.SqlClient;
    using DataLogic;
    using BusEntity;
    
    
    public class PinZhongBusFacade
    {
        
        public PinZhongBusFacade()
        {
        }
        
        // 根据主键coalVarietyID返回指定的PinZhong实体
        public static PinZhongBusEntity GetEntity(int coalVarietyID)
        {
            PinZhongByPK exec = new PinZhongByPK();
            exec.CoalVarietyID = coalVarietyID;
            PinZhongBusEntity obj = new PinZhongBusEntity();
            obj.MetaDataTable = exec.ExecDataTable();
            return obj;
        }
        
        // 返回所有PinZhong
        public static DataTable GetList()
        {
            PinZhongByAll exec = new PinZhongByAll();
            return exec.ExecDataTable();
        }
    }
}
