//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusFacade
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Reflection;
    using System.Data.SqlClient;
    using DataLogic;
    using BusEntity;
    
    
    public class UsersBusFacade
    {
        
        public UsersBusFacade()
        {
        }
        
        // 根据主键userID返回指定的Users实体
        public static UsersBusEntity GetEntity(int userID)
        {
            UsersByPK exec = new UsersByPK();
            exec.UserID = userID;
            UsersBusEntity obj = new UsersBusEntity();
            obj.MetaDataTable = exec.ExecDataTable();
            return obj;
        }
        // 根据主键userID返回指定的Users实体
        public static UsersBusEntity GetEntity(string userName)
        {
            UsersByUserName exec = new UsersByUserName();
            exec.Username = userName;
            UsersBusEntity obj = new UsersBusEntity();
            obj.MetaDataTable = exec.ExecDataTable();
            return obj;
        }
        // 根据主键userName和userPwd返回指定的Users实体
        public static UsersBusEntity GetEntity(string userName,string userPwd)
        {
            UsersByUserNameAndUserPwd exec = new UsersByUserNameAndUserPwd();
            exec.Username = userName;
            exec.Userpwd = userPwd;
            UsersBusEntity obj = new UsersBusEntity();
            obj.MetaDataTable = exec.ExecDataTable();
            return obj;
        }
        // 返回所有Users
        public static DataTable GetList()
        {
            UsersByAll exec = new UsersByAll();
            return exec.ExecDataTable();
        }
    }
}
