//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class PinZhongDataEntity : BaseEntity
    {
        
        public PinZhongDataEntity()
        {
        }
        
        private int m_CoalVarietyID;
        
        public int CoalVarietyID
        {
            get
            {
return this.m_CoalVarietyID;
            }
            set
            {
this.m_CoalVarietyID = value;
            }
        }
        
        private string m_CoalVarietyName;
        
        public string CoalVarietyName
        {
            get
            {
return this.m_CoalVarietyName;
            }
            set
            {
this.m_CoalVarietyName = value;
            }
        }
    }
}
