//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class MeiTanByUserID : BaseExecute
    {
        
        private SqlParameter paraUserid;
        
        public int Userid
        {
            get
            {
return (System.Int32)this.paraUserid.Value;
            }
            set
            {
this.paraUserid.Value = value;
            }
        }
        
        public MeiTanByUserID()
        {
base.InitCommand("MeiTanByUserID");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraUserid = new SqlParameter();
this.paraUserid.ParameterName = "@Userid";
this.paraUserid.SqlDbType = SqlDbType.Int;
this.paraUserid.Size = 4;
this.paraUserid.Direction = ParameterDirection.Input;
this.paraUserid.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserid);
        }
        #endregion
    }
}
