//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class MeiZhongUpdate : BaseExecute
    {
        
        private SqlParameter paraCoalClassID;
        
        public int CoalClassID
        {
            get
            {
return (System.Int32)this.paraCoalClassID.Value;
            }
            set
            {
this.paraCoalClassID.Value = value;
            }
        }
        
        private SqlParameter paraCoalClassName;
        
        public string CoalClassName
        {
            get
            {
return (System.String)this.paraCoalClassName.Value;
            }
            set
            {
this.paraCoalClassName.Value = value;
            }
        }
        
        public MeiZhongUpdate()
        {
base.InitCommand("MeiZhongUpdate");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraCoalClassID = new SqlParameter();
this.paraCoalClassID.ParameterName = "@CoalClassID";
this.paraCoalClassID.SqlDbType = SqlDbType.Int;
this.paraCoalClassID.Size = 4;
this.paraCoalClassID.Direction = ParameterDirection.Input;
this.paraCoalClassID.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraCoalClassID);
//--------------------------------------------------------
this.paraCoalClassName = new SqlParameter();
this.paraCoalClassName.ParameterName = "@CoalClassName";
this.paraCoalClassName.SqlDbType = SqlDbType.VarChar;
this.paraCoalClassName.Size = 50;
this.paraCoalClassName.Direction = ParameterDirection.Input;
this.paraCoalClassName.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraCoalClassName);
        }
        #endregion
    }
}
