//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class QiYeXinXiUpdate : BaseExecute
    {
        
        private SqlParameter paraUserID;
        
        public int UserID
        {
            get
            {
return (System.Int32)this.paraUserID.Value;
            }
            set
            {
this.paraUserID.Value = value;
            }
        }
        
        private SqlParameter paraGSMingCheng;
        
        public string GSMingCheng
        {
            get
            {
return (System.String)this.paraGSMingCheng.Value;
            }
            set
            {
this.paraGSMingCheng.Value = value;
            }
        }
        
        private SqlParameter paraGSXingZhi;
        
        public string GSXingZhi
        {
            get
            {
return (System.String)this.paraGSXingZhi.Value;
            }
            set
            {
this.paraGSXingZhi.Value = value;
            }
        }
        
        private SqlParameter paraQiYeLeiXing;
        
        public string QiYeLeiXing
        {
            get
            {
return (System.String)this.paraQiYeLeiXing.Value;
            }
            set
            {
this.paraQiYeLeiXing.Value = value;
            }
        }
        
        private SqlParameter paraChengLiRiQi;
        
        public System.DateTime ChengLiRiQi
        {
            get
            {
return (System.DateTime)this.paraChengLiRiQi.Value;
            }
            set
            {
this.paraChengLiRiQi.Value = value;
            }
        }
        
        private SqlParameter paraZhuCeZiJin;
        
        public int ZhuCeZiJin
        {
            get
            {
return (System.Int32)this.paraZhuCeZiJin.Value;
            }
            set
            {
this.paraZhuCeZiJin.Value = value;
            }
        }
        
        private SqlParameter paraFaRenDaiBiao;
        
        public string FaRenDaiBiao
        {
            get
            {
return (System.String)this.paraFaRenDaiBiao.Value;
            }
            set
            {
this.paraFaRenDaiBiao.Value = value;
            }
        }
        
        private SqlParameter paraGSJieShao;
        
        public string GSJieShao
        {
            get
            {
return (System.String)this.paraGSJieShao.Value;
            }
            set
            {
this.paraGSJieShao.Value = value;
            }
        }
        
        private SqlParameter paraJingYingFanWei;
        
        public string JingYingFanWei
        {
            get
            {
return (System.String)this.paraJingYingFanWei.Value;
            }
            set
            {
this.paraJingYingFanWei.Value = value;
            }
        }
        
        public QiYeXinXiUpdate()
        {
base.InitCommand("QiYeXinXiUpdate");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraUserID = new SqlParameter();
this.paraUserID.ParameterName = "@UserID";
this.paraUserID.SqlDbType = SqlDbType.Int;
this.paraUserID.Size = 4;
this.paraUserID.Direction = ParameterDirection.Input;
this.paraUserID.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserID);
//--------------------------------------------------------
this.paraGSMingCheng = new SqlParameter();
this.paraGSMingCheng.ParameterName = "@GSMingCheng";
this.paraGSMingCheng.SqlDbType = SqlDbType.NVarChar;
this.paraGSMingCheng.Size = 40;
this.paraGSMingCheng.Direction = ParameterDirection.Input;
this.paraGSMingCheng.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraGSMingCheng);
//--------------------------------------------------------
this.paraGSXingZhi = new SqlParameter();
this.paraGSXingZhi.ParameterName = "@GSXingZhi";
this.paraGSXingZhi.SqlDbType = SqlDbType.NVarChar;
this.paraGSXingZhi.Size = 50;
this.paraGSXingZhi.Direction = ParameterDirection.Input;
this.paraGSXingZhi.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraGSXingZhi);
//--------------------------------------------------------
this.paraQiYeLeiXing = new SqlParameter();
this.paraQiYeLeiXing.ParameterName = "@QiYeLeiXing";
this.paraQiYeLeiXing.SqlDbType = SqlDbType.NVarChar;
this.paraQiYeLeiXing.Size = 50;
this.paraQiYeLeiXing.Direction = ParameterDirection.Input;
this.paraQiYeLeiXing.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraQiYeLeiXing);
//--------------------------------------------------------
this.paraChengLiRiQi = new SqlParameter();
this.paraChengLiRiQi.ParameterName = "@ChengLiRiQi";
this.paraChengLiRiQi.SqlDbType = SqlDbType.DateTime;
this.paraChengLiRiQi.Size = 8;
this.paraChengLiRiQi.Direction = ParameterDirection.Input;
this.paraChengLiRiQi.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraChengLiRiQi);
//--------------------------------------------------------
this.paraZhuCeZiJin = new SqlParameter();
this.paraZhuCeZiJin.ParameterName = "@ZhuCeZiJin";
this.paraZhuCeZiJin.SqlDbType = SqlDbType.Int;
this.paraZhuCeZiJin.Size = 4;
this.paraZhuCeZiJin.Direction = ParameterDirection.Input;
this.paraZhuCeZiJin.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraZhuCeZiJin);
//--------------------------------------------------------
this.paraFaRenDaiBiao = new SqlParameter();
this.paraFaRenDaiBiao.ParameterName = "@FaRenDaiBiao";
this.paraFaRenDaiBiao.SqlDbType = SqlDbType.NVarChar;
this.paraFaRenDaiBiao.Size = 20;
this.paraFaRenDaiBiao.Direction = ParameterDirection.Input;
this.paraFaRenDaiBiao.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraFaRenDaiBiao);
//--------------------------------------------------------
this.paraGSJieShao = new SqlParameter();
this.paraGSJieShao.ParameterName = "@GSJieShao";
this.paraGSJieShao.SqlDbType = SqlDbType.NVarChar;
this.paraGSJieShao.Size = 4000;
this.paraGSJieShao.Direction = ParameterDirection.Input;
this.paraGSJieShao.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraGSJieShao);
//--------------------------------------------------------
this.paraJingYingFanWei = new SqlParameter();
this.paraJingYingFanWei.ParameterName = "@JingYingFanWei";
this.paraJingYingFanWei.SqlDbType = SqlDbType.NVarChar;
this.paraJingYingFanWei.Size = 4000;
this.paraJingYingFanWei.Direction = ParameterDirection.Input;
this.paraJingYingFanWei.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraJingYingFanWei);
        }
        #endregion
    }
}
