//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class CityByPK : BaseExecute
    {
        
        private SqlParameter paraCityName;
        
        public string CityName
        {
            get
            {
return (System.String)this.paraCityName.Value;
            }
            set
            {
this.paraCityName.Value = value;
            }
        }
        
        public CityByPK()
        {
base.InitCommand("CityByPK");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraCityName = new SqlParameter();
this.paraCityName.ParameterName = "@CityName";
this.paraCityName.SqlDbType = SqlDbType.VarChar;
this.paraCityName.Size = 50;
this.paraCityName.Direction = ParameterDirection.Input;
this.paraCityName.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraCityName);
        }
        #endregion
    }
}
