//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class LianXiXinXiByPK : BaseExecute
    {
        
        private SqlParameter paraUserID;
        
        public int UserID
        {
            get
            {
return (System.Int32)this.paraUserID.Value;
            }
            set
            {
this.paraUserID.Value = value;
            }
        }
        
        public LianXiXinXiByPK()
        {
base.InitCommand("LianXiXinXiByPK");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraUserID = new SqlParameter();
this.paraUserID.ParameterName = "@UserID";
this.paraUserID.SqlDbType = SqlDbType.Int;
this.paraUserID.Size = 4;
this.paraUserID.Direction = ParameterDirection.Input;
this.paraUserID.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserID);
        }
        #endregion
    }
}
