//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class LianXiXinXiInsert : BaseExecute
    {
        
        private SqlParameter paraUserID;
        
        public int UserID
        {
            get
            {
return (System.Int32)this.paraUserID.Value;
            }
            set
            {
this.paraUserID.Value = value;
            }
        }
        
        private SqlParameter paraLianXiRen;
        
        public string LianXiRen
        {
            get
            {
return (System.String)this.paraLianXiRen.Value;
            }
            set
            {
this.paraLianXiRen.Value = value;
            }
        }
        
        private SqlParameter paraPhone;
        
        public string Phone
        {
            get
            {
return (System.String)this.paraPhone.Value;
            }
            set
            {
this.paraPhone.Value = value;
            }
        }
        
        private SqlParameter paraMail;
        
        public string Mail
        {
            get
            {
return (System.String)this.paraMail.Value;
            }
            set
            {
this.paraMail.Value = value;
            }
        }
        
        private SqlParameter paraFax;
        
        public string Fax
        {
            get
            {
return (System.String)this.paraFax.Value;
            }
            set
            {
this.paraFax.Value = value;
            }
        }
        
        private SqlParameter paraMobile;
        
        public string Mobile
        {
            get
            {
return (System.String)this.paraMobile.Value;
            }
            set
            {
this.paraMobile.Value = value;
            }
        }
        
        private SqlParameter paraProvince;
        
        public string Province
        {
            get
            {
return (System.String)this.paraProvince.Value;
            }
            set
            {
this.paraProvince.Value = value;
            }
        }
        
        private SqlParameter paraCity;
        
        public string City
        {
            get
            {
return (System.String)this.paraCity.Value;
            }
            set
            {
this.paraCity.Value = value;
            }
        }
        
        private SqlParameter paraAddress;
        
        public string Address
        {
            get
            {
return (System.String)this.paraAddress.Value;
            }
            set
            {
this.paraAddress.Value = value;
            }
        }
        
        private SqlParameter paraPostCode;
        
        public string PostCode
        {
            get
            {
return (System.String)this.paraPostCode.Value;
            }
            set
            {
this.paraPostCode.Value = value;
            }
        }
        
        private SqlParameter paraSiteUrl;
        
        public string SiteUrl
        {
            get
            {
return (System.String)this.paraSiteUrl.Value;
            }
            set
            {
this.paraSiteUrl.Value = value;
            }
        }
        
        public LianXiXinXiInsert()
        {
base.InitCommand("LianXiXinXiInsert");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraUserID = new SqlParameter();
this.paraUserID.ParameterName = "@UserID";
this.paraUserID.SqlDbType = SqlDbType.Int;
this.paraUserID.Size = 4;
this.paraUserID.Direction = ParameterDirection.Input;
this.paraUserID.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserID);
//--------------------------------------------------------
this.paraLianXiRen = new SqlParameter();
this.paraLianXiRen.ParameterName = "@LianXiRen";
this.paraLianXiRen.SqlDbType = SqlDbType.NVarChar;
this.paraLianXiRen.Size = 20;
this.paraLianXiRen.Direction = ParameterDirection.Input;
this.paraLianXiRen.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraLianXiRen);
//--------------------------------------------------------
this.paraPhone = new SqlParameter();
this.paraPhone.ParameterName = "@Phone";
this.paraPhone.SqlDbType = SqlDbType.NVarChar;
this.paraPhone.Size = 20;
this.paraPhone.Direction = ParameterDirection.Input;
this.paraPhone.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraPhone);
//--------------------------------------------------------
this.paraMail = new SqlParameter();
this.paraMail.ParameterName = "@Mail";
this.paraMail.SqlDbType = SqlDbType.NVarChar;
this.paraMail.Size = 50;
this.paraMail.Direction = ParameterDirection.Input;
this.paraMail.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraMail);
//--------------------------------------------------------
this.paraFax = new SqlParameter();
this.paraFax.ParameterName = "@Fax";
this.paraFax.SqlDbType = SqlDbType.NVarChar;
this.paraFax.Size = 20;
this.paraFax.Direction = ParameterDirection.Input;
this.paraFax.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraFax);
//--------------------------------------------------------
this.paraMobile = new SqlParameter();
this.paraMobile.ParameterName = "@Mobile";
this.paraMobile.SqlDbType = SqlDbType.NVarChar;
this.paraMobile.Size = 20;
this.paraMobile.Direction = ParameterDirection.Input;
this.paraMobile.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraMobile);
//--------------------------------------------------------
this.paraProvince = new SqlParameter();
this.paraProvince.ParameterName = "@Province";
this.paraProvince.SqlDbType = SqlDbType.NVarChar;
this.paraProvince.Size = 50;
this.paraProvince.Direction = ParameterDirection.Input;
this.paraProvince.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraProvince);
//--------------------------------------------------------
this.paraCity = new SqlParameter();
this.paraCity.ParameterName = "@City";
this.paraCity.SqlDbType = SqlDbType.NVarChar;
this.paraCity.Size = 50;
this.paraCity.Direction = ParameterDirection.Input;
this.paraCity.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraCity);
//--------------------------------------------------------
this.paraAddress = new SqlParameter();
this.paraAddress.ParameterName = "@Address";
this.paraAddress.SqlDbType = SqlDbType.NVarChar;
this.paraAddress.Size = 50;
this.paraAddress.Direction = ParameterDirection.Input;
this.paraAddress.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraAddress);
//--------------------------------------------------------
this.paraPostCode = new SqlParameter();
this.paraPostCode.ParameterName = "@PostCode";
this.paraPostCode.SqlDbType = SqlDbType.NVarChar;
this.paraPostCode.Size = 6;
this.paraPostCode.Direction = ParameterDirection.Input;
this.paraPostCode.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraPostCode);
//--------------------------------------------------------
this.paraSiteUrl = new SqlParameter();
this.paraSiteUrl.ParameterName = "@SiteUrl";
this.paraSiteUrl.SqlDbType = SqlDbType.Char;
this.paraSiteUrl.Size = 100;
this.paraSiteUrl.Direction = ParameterDirection.Input;
this.paraSiteUrl.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraSiteUrl);
        }
        #endregion
    }
}
