//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class UsersInsert : BaseExecute
    {
        
        private SqlParameter paraUserID;
        
        public int UserID
        {
            get
            {
return (System.Int32)this.paraUserID.Value;
            }
            set
            {
this.paraUserID.Value = value;
            }
        }
        
        private SqlParameter paraUserName;
        
        public string UserName
        {
            get
            {
return (System.String)this.paraUserName.Value;
            }
            set
            {
this.paraUserName.Value = value;
            }
        }
        
        private SqlParameter paraUserPwd;
        
        public string UserPwd
        {
            get
            {
return (System.String)this.paraUserPwd.Value;
            }
            set
            {
this.paraUserPwd.Value = value;
            }
        }
        
        private SqlParameter paraUserMail;
        
        public string UserMail
        {
            get
            {
return (System.String)this.paraUserMail.Value;
            }
            set
            {
this.paraUserMail.Value = value;
            }
        }
        
        private SqlParameter paraUserQ;
        
        public string UserQ
        {
            get
            {
return (System.String)this.paraUserQ.Value;
            }
            set
            {
this.paraUserQ.Value = value;
            }
        }
        
        private SqlParameter paraUserA;
        
        public string UserA
        {
            get
            {
return (System.String)this.paraUserA.Value;
            }
            set
            {
this.paraUserA.Value = value;
            }
        }
        
        private SqlParameter paraIsFormal;
        
        public bool IsFormal
        {
            get
            {
return (System.Boolean)this.paraIsFormal.Value;
            }
            set
            {
this.paraIsFormal.Value = value;
            }
        }
        
        private SqlParameter paraCreatDate;
        
        public System.DateTime CreatDate
        {
            get
            {
return (System.DateTime)this.paraCreatDate.Value;
            }
            set
            {
this.paraCreatDate.Value = value;
            }
        }
        
        public UsersInsert()
        {
base.InitCommand("UsersInsert");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraUserID = new SqlParameter();
this.paraUserID.ParameterName = "@UserID";
this.paraUserID.SqlDbType = SqlDbType.Int;
this.paraUserID.Size = 4;
this.paraUserID.Direction = ParameterDirection.Output;
base.m_cmd.Parameters.Add(this.paraUserID);
//--------------------------------------------------------
this.paraUserName = new SqlParameter();
this.paraUserName.ParameterName = "@UserName";
this.paraUserName.SqlDbType = SqlDbType.NVarChar;
this.paraUserName.Size = 20;
this.paraUserName.Direction = ParameterDirection.Input;
this.paraUserName.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserName);
//--------------------------------------------------------
this.paraUserPwd = new SqlParameter();
this.paraUserPwd.ParameterName = "@UserPwd";
this.paraUserPwd.SqlDbType = SqlDbType.NVarChar;
this.paraUserPwd.Size = 20;
this.paraUserPwd.Direction = ParameterDirection.Input;
this.paraUserPwd.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserPwd);
//--------------------------------------------------------
this.paraUserMail = new SqlParameter();
this.paraUserMail.ParameterName = "@UserMail";
this.paraUserMail.SqlDbType = SqlDbType.NVarChar;
this.paraUserMail.Size = 50;
this.paraUserMail.Direction = ParameterDirection.Input;
this.paraUserMail.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserMail);
//--------------------------------------------------------
this.paraUserQ = new SqlParameter();
this.paraUserQ.ParameterName = "@UserQ";
this.paraUserQ.SqlDbType = SqlDbType.NVarChar;
this.paraUserQ.Size = 30;
this.paraUserQ.Direction = ParameterDirection.Input;
this.paraUserQ.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserQ);
//--------------------------------------------------------
this.paraUserA = new SqlParameter();
this.paraUserA.ParameterName = "@UserA";
this.paraUserA.SqlDbType = SqlDbType.NVarChar;
this.paraUserA.Size = 30;
this.paraUserA.Direction = ParameterDirection.Input;
this.paraUserA.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserA);
//--------------------------------------------------------
this.paraIsFormal = new SqlParameter();
this.paraIsFormal.ParameterName = "@IsFormal";
this.paraIsFormal.SqlDbType = SqlDbType.Bit;
this.paraIsFormal.Size = 1;
this.paraIsFormal.Direction = ParameterDirection.Input;
this.paraIsFormal.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraIsFormal);
//--------------------------------------------------------
this.paraCreatDate = new SqlParameter();
this.paraCreatDate.ParameterName = "@CreatDate";
this.paraCreatDate.SqlDbType = SqlDbType.DateTime;
this.paraCreatDate.Size = 8;
this.paraCreatDate.Direction = ParameterDirection.Input;
this.paraCreatDate.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraCreatDate);
        }
        #endregion
    }
}
