//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;
    
    
    public class WenZhangLiuYanInsert : BaseExecute
    {
        
        private SqlParameter paraID;
        
        public int ID
        {
            get
            {
return (System.Int32)this.paraID.Value;
            }
            set
            {
this.paraID.Value = value;
            }
        }
        
        private SqlParameter paraPinDaoId;
        
        public int PinDaoId
        {
            get
            {
return (System.Int32)this.paraPinDaoId.Value;
            }
            set
            {
this.paraPinDaoId.Value = value;
            }
        }
        
        private SqlParameter paraWenZhangId;
        
        public int WenZhangId
        {
            get
            {
return (System.Int32)this.paraWenZhangId.Value;
            }
            set
            {
this.paraWenZhangId.Value = value;
            }
        }
        
        private SqlParameter paraLiuYanNeiRong;
        
        public string LiuYanNeiRong
        {
            get
            {
return (System.String)this.paraLiuYanNeiRong.Value;
            }
            set
            {
this.paraLiuYanNeiRong.Value = value;
            }
        }
        
        private SqlParameter paraUserID;
        
        public int UserID
        {
            get
            {
return (System.Int32)this.paraUserID.Value;
            }
            set
            {
this.paraUserID.Value = value;
            }
        }
        
        private SqlParameter paraShiJian;
        
        public System.DateTime ShiJian
        {
            get
            {
return (System.DateTime)this.paraShiJian.Value;
            }
            set
            {
this.paraShiJian.Value = value;
            }
        }
        
        private SqlParameter paraIsDelete;
        
        public bool IsDelete
        {
            get
            {
return (System.Boolean)this.paraIsDelete.Value;
            }
            set
            {
this.paraIsDelete.Value = value;
            }
        }
        
        public WenZhangLiuYanInsert()
        {
base.InitCommand("WenZhangLiuYanInsert");
ConfigParameter();
        }
        
        #region 存储过程参数赋值
        public void ConfigParameter()
        {
//--------------------------------------------------------
this.paraID = new SqlParameter();
this.paraID.ParameterName = "@ID";
this.paraID.SqlDbType = SqlDbType.Int;
this.paraID.Size = 4;
this.paraID.Direction = ParameterDirection.Output;
base.m_cmd.Parameters.Add(this.paraID);
//--------------------------------------------------------
this.paraPinDaoId = new SqlParameter();
this.paraPinDaoId.ParameterName = "@PinDaoId";
this.paraPinDaoId.SqlDbType = SqlDbType.Int;
this.paraPinDaoId.Size = 4;
this.paraPinDaoId.Direction = ParameterDirection.Input;
this.paraPinDaoId.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraPinDaoId);
//--------------------------------------------------------
this.paraWenZhangId = new SqlParameter();
this.paraWenZhangId.ParameterName = "@WenZhangId";
this.paraWenZhangId.SqlDbType = SqlDbType.Int;
this.paraWenZhangId.Size = 4;
this.paraWenZhangId.Direction = ParameterDirection.Input;
this.paraWenZhangId.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraWenZhangId);
//--------------------------------------------------------
this.paraLiuYanNeiRong = new SqlParameter();
this.paraLiuYanNeiRong.ParameterName = "@LiuYanNeiRong";
this.paraLiuYanNeiRong.SqlDbType = SqlDbType.NVarChar;
this.paraLiuYanNeiRong.Size = 100;
this.paraLiuYanNeiRong.Direction = ParameterDirection.Input;
this.paraLiuYanNeiRong.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraLiuYanNeiRong);
//--------------------------------------------------------
this.paraUserID = new SqlParameter();
this.paraUserID.ParameterName = "@UserID";
this.paraUserID.SqlDbType = SqlDbType.Int;
this.paraUserID.Size = 4;
this.paraUserID.Direction = ParameterDirection.Input;
this.paraUserID.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraUserID);
//--------------------------------------------------------
this.paraShiJian = new SqlParameter();
this.paraShiJian.ParameterName = "@ShiJian";
this.paraShiJian.SqlDbType = SqlDbType.DateTime;
this.paraShiJian.Size = 8;
this.paraShiJian.Direction = ParameterDirection.Input;
this.paraShiJian.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraShiJian);
//--------------------------------------------------------
this.paraIsDelete = new SqlParameter();
this.paraIsDelete.ParameterName = "@IsDelete";
this.paraIsDelete.SqlDbType = SqlDbType.Bit;
this.paraIsDelete.Size = 1;
this.paraIsDelete.Direction = ParameterDirection.Input;
this.paraIsDelete.Value=DBNull.Value;
base.m_cmd.Parameters.Add(this.paraIsDelete);
        }
        #endregion
    }
}
