//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusRule
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Reflection;
    using System.Data.SqlClient;
    using DataLogic;
    using BusEntity;
    using BusFacade;
    
    
    // [Transaction(TransactionOption.Required)]
    public class GongShiXingZhiBusRule
    {
        
        public GongShiXingZhiBusRule()
        {
        }
        
        #region 公有全局方法insert/update/delete
        // 添加由实体指定的一条记录 AddGongShiXingZhi
        public bool Add(GongShiXingZhiBusEntity obj)
        {
            return InsertEntity(obj);
        }
        
        // 修改由实体指定的一条记录 ModifyGongShiXingZhi
        public bool Modify(GongShiXingZhiBusEntity obj)
        {
            return UpdateEntity(obj);
        }
        
        // 物理删除由主键ID指定的一条记录 DeleteGongShiXingZhi
        public bool Delete(int ID)
        {
            GongShiXingZhiDelete exec = new GongShiXingZhiDelete();
            try
            {
                exec.ID = ID;
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                exec = null;
            }
        }
        #endregion
        
        #region 公有静态全局方法insert/update/delete
        // 公用静态方法，插入一条记录 InsertGongShiXingZhi
        public static bool InsertEntity(GongShiXingZhiBusEntity obj)
        {
            GongShiXingZhiInsert exec = new GongShiXingZhiInsert();
            try
            {
                exec.ReceiveParameter(obj);
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                obj = null;
            }
        }
        
        // 公用静态方法，修改一条记录 UpdateGongShiXingZhi
        public static bool UpdateEntity(GongShiXingZhiBusEntity obj)
        {
            if (obj == null || obj.IsEmpty)
            {
                return false;
            }
            GongShiXingZhiUpdate exec = new GongShiXingZhiUpdate();
            try
            {
                exec.ReceiveParameter(obj);
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                obj = null;
            }
        }
        
        // 公用静态方法，删除一条记录 DeleteGongShiXingZhi
        public static bool DeleteEntity(GongShiXingZhiBusEntity obj)
        {
            if (obj == null || obj.IsEmpty)
            {
                return false;
            }
            GongShiXingZhiDelete exec = new GongShiXingZhiDelete();
            try
            {
                exec.ReceiveParameter(obj);
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                obj = null;
            }
        }
        #endregion
    }
}
