//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusRule
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Reflection;
    using System.Data.SqlClient;
    using DataLogic;
    using BusEntity;
    using BusFacade;
    
    
    // [Transaction(TransactionOption.Required)]
    public class PinZhongBusRule
    {
        
        public PinZhongBusRule()
        {
        }
        
        #region 公有全局方法insert/update/delete
        // 添加由实体指定的一条记录 AddPinZhong
        public bool Add(PinZhongBusEntity obj)
        {
            return InsertEntity(obj);
        }
        
        // 修改由实体指定的一条记录 ModifyPinZhong
        public bool Modify(PinZhongBusEntity obj)
        {
            return UpdateEntity(obj);
        }
        
        // 物理删除由主键coalVarietyID指定的一条记录 DeletePinZhong
        public bool Delete(int coalVarietyID)
        {
            PinZhongDelete exec = new PinZhongDelete();
            try
            {
                exec.CoalVarietyID = coalVarietyID;
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                exec = null;
            }
        }
        #endregion
        
        #region 公有静态全局方法insert/update/delete
        // 公用静态方法，插入一条记录 InsertPinZhong
        public static bool InsertEntity(PinZhongBusEntity obj)
        {
            PinZhongInsert exec = new PinZhongInsert();
            try
            {
                exec.ReceiveParameter(obj);
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                obj = null;
            }
        }
        
        // 公用静态方法，修改一条记录 UpdatePinZhong
        public static bool UpdateEntity(PinZhongBusEntity obj)
        {
            if (obj == null || obj.IsEmpty)
            {
                return false;
            }
            PinZhongUpdate exec = new PinZhongUpdate();
            try
            {
                exec.ReceiveParameter(obj);
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                obj = null;
            }
        }
        
        // 公用静态方法，删除一条记录 DeletePinZhong
        public static bool DeleteEntity(PinZhongBusEntity obj)
        {
            if (obj == null || obj.IsEmpty)
            {
                return false;
            }
            PinZhongDelete exec = new PinZhongDelete();
            try
            {
                exec.ReceiveParameter(obj);
                exec.ExecNoQuery();
                return true;
            }
            catch (Exception ex)
            {
                //throw ex;
                return false;
            }
            finally
            {
                obj = null;
            }
        }
        #endregion
    }
}
