<div id="h_header">
	<h1 class="logo"><a href="index.html" title="国家煤炭工业网">国家煤炭工业网</a></h1>
	<div class="h_topNav">
		<div class="h_r1"></div>
		<div class="h_navList"><a href="index.html">网站首页</a> | <a href="#">我要采购</a> | <a href="#">我要销售</a> | <a href="#">资讯</a> | <a href="#">论坛</a></div>
		<div class="h_r1"></div>
	</div>
	<div class="h_mainMenu clearfix">
		<ul class="h_mainNav">
			<li class="current"><a href="#">系统首页</a></li>
		</ul>
		<div class="h_userInfo"><span id="welcome">[<a id="log_out" href="log_out.aspx">退出系统</a>]</span></div>
		<div class="h_userExplain"><a id="user_type" href="#"></a></div>
	</div>
</div>
